### ISSUE TITLE
[CHORE] jacoco를 이용한 코드 커버리지 적용.

### ISSUE THREAD

**Issue by twotwobread** [prgrms-web-devcourse/Team-6Jeans-Hype-BE#3]
- build.gradle 파일에 task 추가. -> 초기 라인 커버리지, 브랜치 커버리지 0퍼로 설정. (추후 50퍼로 변경 예정)
  - 코드 커버리지 50퍼로 설정 이유 : 테스트를 짜는 이유가 커버리지를 채우기 위함이 되어서는 안된다고 생각. -> 좋은 부정 지표로써의 사용을 위함. 
- 코드 커버리지에서 lombok 어노테이션 제거를 위한 설정 파일 추가.

**Comment by park-se-jun** [comment]
완료된 이슈
